---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(vegan)
library(broom)
library(DESeq2)
```
## Data Import
### Load in the data
```{r}
counts <- read_rds("~/JOE/HALLII/RIL/asv_table16ParentsM2nova.rds")
parent_data <- read_csv("~/JOE/HALLII/RIL/ril_m_data.csv") %>% 
  dplyr::select(-c(ASVID, RA, value)) %>% distinct() %>% 
  filter(SampleID%in%rownames(counts))
tax <- read_rds("~/JOE/HALLII/RIL/tax16ParentsMnova2.rds") %>% 
  as.data.frame() %>% rownames_to_column("Seq") %>% as_tibble() %>% 
  mutate(ASVID = paste0("hASV", 1:nrow(.))) %>% 
  mutate(Phylum2 = ifelse(Phylum == "Proteobacteria", paste("Proteobacteria", as.character(Class)), as.character(Phylum)))
colnames(counts) <- tax$ASVID
organelle <- tax %>% filter(grepl("Mitochon", Family) | grepl("Chloroplast", Order)) %>% pull(ASVID)
```

### Format the data
```{r}
spread_data <- counts_tidy %>% 
  mutate(TRT_MS = ifelse(TRT == "AUS18", "AustinF", TRT_MS),
         TRT_MS = ifelse(TRT == "Corpus18", "CorpusFF", TRT_MS)) %>% 
  filter(!is.na(TRT_MS) & !ASVID%in%organelle) %>% 
  dplyr::select(SampleID, Compartment, Location, TRT_MS, Time, TRT2, TRT, ASVID, value) %>% 
  group_by(ASVID) %>% filter(sum(value > 0) / n() > 0.05) %>% 
  filter(Time != "Middle" & Time != "Begin") %>% 
  spread(ASVID, value) %>% 
  group_by(SampleID) %>%
  mutate(rank = 1:n()) %>% 
  filter(rank == 1)

spread_info <- spread_data %>% 
  dplyr::select(SampleID, Compartment, Location, TRT_MS, Time, TRT2, TRT) %>% 
  mutate(condition = paste(TRT_MS, Compartment, sep = "_")) %>% 
  mutate(location = ifelse(grepl("Corpus|AUS", TRT), "Field", "Greenhouse")) %>% 
  column_to_rownames('SampleID') 

spread_df <- spread_data %>% 
  dplyr::select(-c(Compartment, Location, TRT_MS, Time, TRT2, TRT)) %>% 
  column_to_rownames('SampleID')
```


## Field analysis
### Shannon diversity
```{r}
# This shannon object will be used later for the greenhouse experiments as well
shannon <- as.data.frame(diversity(counts)) %>% 
  rownames_to_column("SampleID") %>% 
  dplyr::rename(shannon = 2) %>% 
  inner_join(parent_data, by = "SampleID")

field_diversity <- shannon %>% 
  filter(TRT %in% c("Corpus19", "AUS19")) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Root", "Rhizo", "Soil")) %>% 
  ggplot(aes(Compartment, shannon, color = TRT_MS)) +
  geom_boxplot() +
  geom_point(position = position_jitterdodge(jitter.width = 0.2)) +
  theme_minimal() +
  coord_flip() +
  scale_color_manual(values = c("red", "steelblue"))
```
### PCoA
```{r}
field_info <- spread_info %>% filter(TRT_MS %in% c("AustinF", "CorpusF", "CorpusFF")) %>% rownames_to_column("SampleID") %>% 
  filter(!TRT %in% c("AUS18", "Corpus18"))
field_ra <- spread_df_ra %>% rownames_to_column("SampleID") %>% right_join(field_info %>% dplyr::select(SampleID)) %>% column_to_rownames("SampleID")
field_pc <- capscale(log2(field_ra + 1) ~ 1, distance = "bray")
field_pcoa <- field_pc$CA$u[,1:5] %>% as.data.frame() %>% 
  bind_cols(field_info) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  ggplot(aes(MDS1, MDS2, color = TRT, shape = Compartment)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray") +
  theme_minimal() +
  scale_color_brewer(palette = "Set1") +
  labs(x = "PCo1 (23.7%)", y = "PCo2 (21.4%)")
```

### Phylum Analyses
```{r}
field_phy_plot <- counts_tidy %>% 
  filter(SampleID %in% rownames(spread_info)) %>% 
  inner_join(tax, by = "ASVID") %>%
  group_by(SampleID) %>% 
  mutate(RA = value / sum(value) * 1000) %>% 
  group_by(Phylum2, SampleID, Compartment, TRT_MS, TRT, TRT2) %>% 
  filter(TRT %in% c("AUS19", "Corpus19")) %>% 
  summarise(phy_tot = sum(RA)) %>% 
  group_by(Phylum2) %>% nest() %>% 
  mutate(phy_all = map_dbl(data, ~sum(.x$phy_tot))) %>% ungroup() %>% 
  top_n(13, phy_all) %>% unnest(data) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  group_by(Compartment, TRT_MS, Phylum2) %>% 
  summarise(mean_tot = mean(phy_tot)) %>% 
  mutate(Phylum2 = fct_relevel(Phylum2, "Verrucomicrobia", after = 8)) %>% 
  mutate(Phylum2 = fct_relevel(Phylum2, "Thaumarchaeota", after = 8)) %>% 
  filter(!is.na(TRT_MS)) %>% 
  ggplot(aes(Compartment, mean_tot, fill = Phylum2)) + geom_bar(stat = "identity") +
  scale_fill_manual(values = c(RColorBrewer::brewer.pal(12,"Paired")[-c(5,6)], RColorBrewer::brewer.pal(5, "Reds"), "dodgerblue")) +
  facet_grid(.~TRT_MS, scales = "free_x") +
  labs(x = "Sample", y = "Relative abundance (‰)") +
  theme_minimal() +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1))

field_phy_lm <- counts_tidy %>% 
  filter(SampleID %in% rownames(spread_info)) %>% 
  inner_join(tax, by = "ASVID") %>%
  group_by(SampleID) %>% 
  mutate(RA = value / sum(value) * 1000) %>% 
  mutate(location = ifelse(TRT_MS%in%c("AustinF", "CorpusF"), "Field", "Greenhouse")) %>% 
  filter(location == "Field") %>% 
  group_by(Phylum2, SampleID, Compartment, TRT_MS, TRT, TRT2, location) %>% 
  summarise(phy_tot = sum(RA)) %>% 
  #filter(!TRT_MS %in% c("AustinF", "CorpusF")) %>% 
  group_by(Phylum2, Compartment) %>% nest() %>% 
  mutate(mod = map(data, ~tidy(lm(log2(phy_tot + 1) ~ TRT2, .)))) %>% 
  dplyr::select(Compartment, Phylum2, mod) %>%
  unnest(mod)
phy_field_lm_plot <- phy_field_lm %>% 
  filter(term != "(Intercept)") %>% 
  ungroup() %>% 
  group_by(Compartment) %>% 
  mutate(p.adj = p.adjust(p.value)) %>% 
  mutate(sig = ifelse(p.adj < 0.05, "sig", NA)) %>% ungroup() %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  filter(!is.na(Phylum2)) %>% 
  ggplot(aes(Compartment, Phylum2, fill = estimate, alpha = sig)) +
  geom_tile(alpha = 1) +
  geom_tile(aes(color = sig, alpha = sig), size = 0.5, fill = NA) +
  scale_fill_gradient2(low = "red", high = "steelblue") +
  scale_color_manual(values = c("black")) +
  scale_alpha_manual(values = c(0,1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_equal()
field_phy_plot
phy_field_lm_plot
```

### Differentially abundant ASVs
```{r}
dds_soil <- DESeqDataSetFromMatrix(t(spread_df), spread_info, design = ~ condition)
dds_soil <- DESeq(dds_soil) ## This object will also be used for the greenhouse analysis


field_soil <- results(dds_soil, contrast = c("condition", "AustinF_Soil", "CorpusF_Soil")) %>% tidy() %>%
  mutate(Compartment = "Soil")
field_rhizo <- results(dds_soil, contrast = c("condition", "AustinF_Rhizo", "CorpusF_Rhizo")) %>% tidy() %>% 
  mutate(Compartment = "Rhizo")
field_root <- results(dds_soil, contrast = c("condition", "AustinF_Root", "CorpusF_Root")) %>% tidy() %>% 
  mutate(Compartment = "Root")

field_da_plot <- bind_rows(field_soil, field_rhizo, field_root) %>% 
  filter(p.adjusted < 0.05) %>% 
  inner_join(tax, by = c("gene" = "ASVID")) %>% 
  mutate(direction = ifelse(estimate > 0, "Austin", "Corpus")) %>% 
  dplyr::count(Compartment, Phylum, direction) %>% 
  mutate(n2 = ifelse(direction == "Austin", -n, n)) %>% 
  mutate(Phylum = fct_reorder(Phylum, n),
         Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  filter(!is.na(Phylum)) %>% 
  group_by(Phylum) %>% filter(sum(n) > 5) %>% 
  ggplot(aes(Phylum, n2, fill = direction)) +
  geom_bar(stat = "identity") +
  facet_grid(.~Compartment) +
  scale_fill_manual(values = c("red", "steelblue")) +
  coord_flip() +
  theme_minimal()
```

## Greenhouse Analysis
### PCoA
```{r}
gh_info <- spread_info %>% 
  filter(TRT %in% c("AC", "AT", "CC", "CT") & Time == "Harvest") %>% 
  rownames_to_column("SampleID")
gh_ra <- spread_df_ra %>% rownames_to_column("SampleID") %>% right_join(gh_info %>% dplyr::select(SampleID)) %>% column_to_rownames("SampleID")
gh_pc <- capscale(log2(gh_ra + 1) ~ 1, distance = "bray")
gh_pcoa <- gh_pc$CA$u[,1:5] %>% as.data.frame() %>% 
  bind_cols(gh_info) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  ggplot(aes(MDS1, MDS2, color = TRT, shape = Compartment)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray") +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray") +
  geom_point(size = 3, alpha = 0.8) +
  theme_minimal() +
  scale_color_manual(values = c("#FB9A99", "#E31A1C", "#A6CEE3", "#1F78B4")) +
  labs(x = "PCo1 (22.4%)", y = "PCo2 (12.1%)")
```

### Compare BC dissimilarities between treatment levels
```{r}
df_dist <- vegdist(log2(spread_df_ra + 1)) %>% as.matrix()
df_dist[upper.tri(df_dist, diag = T)] <- NA
df_dist_long <- df_dist %>%
  as.data.frame() %>% 
  rownames_to_column("Sample1") %>% 
  gather(Sample2, dist, -Sample1) %>%
  na.omit() %>% 
  inner_join(spread_info %>% rownames_to_column("Sample1"), by = "Sample1") %>% 
  inner_join(spread_info %>% rownames_to_column("Sample2"), by = "Sample2")

gh_dist_comp <- df_dist_long %>% 
  filter(Compartment.x == Compartment.y) %>% 
  mutate(Compartment = Compartment.x) %>% dplyr::select(-c(Compartment.x, Compartment.y)) %>%
  filter(TRT.x%in%c("AC", "AT", "CC", "CT") & TRT.y%in%c("AC", "AT", "CC", "CT")) %>% 
  filter(TRT.x != TRT.y) %>% 
  mutate(type.x = ifelse(TRT.x%in%c("AC", "CC"), "Ambient", "Native"),
         type.y = ifelse(TRT.y%in%c("AC", "CC"), "Ambient", "Native")) %>% 
  filter(type.x == type.y) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  ggplot(aes(Compartment, dist, color = type.x)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point(position = position_jitterdodge(jitter.width = 0.2), alpha = 0.5, size = 1) +
  scale_color_manual(values = c("gray", "black")) +
  labs(x = "", y = "Bray-Curtis Dissimilarity") +
  theme_minimal()
```


### Shannon diversity
```{r}
gh_diversity  <- shannon %>% 
  filter(!TRT %in% c("Corpus19", "AUS19", "Corpus18", "AUS18")) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  ggplot(aes(Compartment, shannon, color = TRT)) +
  geom_boxplot(outlier.alpha = 0) +
  geom_point(position = position_jitterdodge(jitter.width = 0.2), size = 1) +
  theme_minimal() +
  scale_color_manual(values = c("#FB9A99", "#E31A1C", "#A6CEE3", "#1F78B4"))
```

### Phylum level statistics
```{r}
gh_phy_plot <- counts_tidy %>% 
  filter(SampleID %in% rownames(spread_info)) %>% 
  inner_join(tax, by = "ASVID") %>%
  group_by(SampleID) %>% 
  mutate(RA = value / sum(value) * 1000) %>% 
  group_by(Phylum2, SampleID, Compartment, TRT_MS, TRT, TRT2) %>% 
  summarise(phy_tot = sum(RA)) %>% 
  group_by(Phylum2) %>% nest() %>% 
  mutate(phy_all = map_dbl(data, ~sum(.x$phy_tot))) %>% ungroup() %>% 
  top_n(13, phy_all) %>% unnest(data) %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  group_by(Compartment, TRT_MS, Phylum2) %>% 
  summarise(mean_tot = mean(phy_tot)) %>% 
  mutate(Phylum2 = fct_relevel(Phylum2, "Verrucomicrobia", after = 9)) %>% 
  filter(!is.na(TRT_MS) & !TRT_MS%in%c("CorpusF", "AustinF")) %>% 
  ggplot(aes(Compartment, mean_tot, fill = Phylum2)) + geom_bar(stat = "identity") +
  scale_fill_manual(values = c(RColorBrewer::brewer.pal(12,"Paired")[-c(5,6)], RColorBrewer::brewer.pal(5, "Reds"), "dodgerblue")) +
  facet_grid(.~TRT_MS, scales = "free_x") +
  labs(x = "Sample", y = "Relative abundance (‰)") +
  theme_minimal() +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_text(angle = 45, hjust = 1))

gh_phy_lm <- counts_tidy %>% 
  filter(SampleID %in% rownames(spread_info)) %>% 
  inner_join(tax, by = "ASVID") %>%
  group_by(SampleID) %>% 
  mutate(RA = value / sum(value) * 1000) %>% 
  group_by(Phylum2, SampleID, Compartment, TRT_MS, TRT, TRT2) %>% 
  summarise(phy_tot = sum(RA)) %>% 
  filter(!TRT_MS %in% c("AustinF", "CorpusF")) %>% 
  mutate(type = ifelse(TRT%in%c("AT", "CT"), "treated", "null"),
         source = ifelse(TRT%in%c("AC", "AT"), "Austin", "Corpus")) %>%  
  group_by(Phylum2, Compartment, type) %>% nest() %>% 
  mutate(mod = map(data, ~tidy(lm(log2(phy_tot + 1) ~ source, .)))) %>% 
  dplyr::select(Compartment, Phylum2, type, mod) %>%
  unnest(mod)

gh_phy_model_plot <- gh_phy_lm %>% 
  filter(term != "(Intercept)") %>% 
  ungroup() %>% 
  group_by(Compartment) %>% 
  mutate(p.adj = p.adjust(p.value)) %>% 
  mutate(sig = ifelse(p.adj < 0.05, "sig", NA)) %>% ungroup() %>% 
  mutate(Compartment = fct_relevel(Compartment, "Root", "Rhizo", "Soil")) %>% 
  filter(!is.na(Phylum2)) %>% 
  mutate(Phylum2 = gsub("Proteobacteria ", "", Phylum2)) %>% 
  ggplot(aes(Phylum2, Compartment, fill = estimate, alpha = sig)) +
  geom_tile(alpha = 1) +
  geom_tile(aes(color = sig, alpha = sig), size = 0.5, fill = NA) +
  scale_fill_gradient2(low = "red", high = "steelblue") +
  scale_color_manual(values = c("black")) +
  scale_alpha_manual(values = c(0,1)) +
  facet_grid(type~.) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  coord_equal()

gh_phy_plot
gh_phy_model_plot
```

### Differentially abundant ASVs
```{r}
trt_soil <- results(dds_field, contrast = c("condition", "1NativeAUS_Soil", "2NativeCorpus_Soil")) %>% tidy() %>% 
  mutate(Compartment = "Soil", type = "TRT")
trt_rhizo <- results(dds_field, contrast = c("condition", "1NativeAUS_Rhizo", "2NativeCorpus_Rhizo")) %>% tidy() %>% 
  mutate(Compartment = "Rhizo", type = "TRT")
trt_root <- results(dds_field, contrast = c("condition", "1NativeAUS_Root", "2NativeCorpus_Root")) %>% tidy() %>% 
  mutate(Compartment = "Root", type = "TRT")

amb_soil <- results(dds_field, contrast = c("condition", "3AmbAus_Soil", "4AmbCorpus_Soil")) %>% tidy() %>% 
  mutate(Compartment = "Soil", type = "AMB")
amb_rhizo <- results(dds_field, contrast = c("condition", "3AmbAus_Rhizo", "4AmbCorpus_Rhizo")) %>% tidy() %>% 
  mutate(Compartment = "Rhizo", type = "AMB")
amb_root <- results(dds_field, contrast = c("condition", "3AmbAus_Root", "4AmbCorpus_Root")) %>% tidy() %>% 
  mutate(Compartment = "Root", type = "AMB")

gh_da_asv <- bind_rows(
  trt_soil,
  trt_rhizo,
  trt_root,
  amb_soil,
  amb_rhizo,
  amb_root
) %>% 
  dplyr::rename(ASVID = gene) %>% 
  filter(p.adjusted < 0.05) %>% 
  inner_join(tax) %>% 
  mutate(direction = ifelse(estimate > 0, "AUS", "CC")) %>% 
  dplyr::count(Phylum, Compartment, type, direction) %>% 
  mutate(n2 = ifelse(type == "AMB", -n, n)) %>% 
  mutate(Phylum = fct_reorder(Phylum, n),
         comparison = paste(direction, type)) %>% 
  group_by(Phylum, Compartment) %>% 
  filter(sum(n) > 10) %>% ungroup() %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  ggplot(aes(Phylum, n2, fill = comparison)) +
  geom_bar(stat = "identity") + 
  geom_hline(yintercept = 0, size = 0.1) +
  facet_grid(.~Compartment) +
  theme_minimal() +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("#FB9A99", "#E31A1C", "#A6CEE3", "#1F78B4"))
```

## Combined Analysis
### PCoA
```{r}
spread_df_ra <- spread_df / rowSums(spread_df) * 1000
combo_pc <- capscale(log2(spread_df_ra + 1) ~ 1)
head(combo_pc$CA$eig / sum(combo_pc$CA$eig))
combo_pc_plot <- combo_pc$CA$u[,1:5] %>% as.data.frame() %>% 
  bind_cols(spread_info) %>% 
  mutate(
    TRT = gsub("1[89]", "_Field", TRT),
    exper = ifelse(grepl("Orig", Time), "Field", "Greenhouse")
  ) %>% 
  ggplot(aes(MDS1, MDS2, color = TRT, shape = exper)) + 
  geom_point() +
  scale_color_manual(values = c("#FB9A99", "#E31A1C", "#E31A1C", "#A6CEE3", "#1F78B4", "#1F78B4")) +
  scale_shape_manual(values = c(1, 16)) +
  labs(x = "PCo1 (21.7%)", y = "PCo2 (7.8%)") +
  theme_minimal()

combo_pc_plot
```

### Phylum Stats
```{r}
field_gh_lm <- counts_tidy %>% 
  filter(SampleID %in% rownames(spread_info)) %>% 
  inner_join(tax, by = "ASVID") %>%
  group_by(SampleID) %>% 
  mutate(RA = value / sum(value) * 1000) %>% 
  mutate(location = ifelse(TRT_MS%in%c("AustinF", "CorpusF"), "Field", "Greenhouse")) %>% 
  filter(!TRT%in%c("CC", "AC")) %>% 
  group_by(Phylum2, SampleID, Compartment, TRT_MS, TRT, TRT2, location) %>% 
  summarise(phy_tot = sum(RA)) %>% 
  #filter(!TRT_MS %in% c("AustinF", "CorpusF")) %>% 
  group_by(Phylum2, Compartment) %>% nest() %>% 
  mutate(mod = map(data, ~tidy(lm(log2(phy_tot + 1) ~ location, .)))) %>% 
  dplyr::select(Compartment, Phylum2, mod) %>%
  unnest(mod)

field_gh_comp <- field_gh_lm %>% 
  filter(term != "(Intercept)") %>% 
  ungroup() %>% 
  group_by(Compartment) %>% 
  mutate(p.adj = p.adjust(p.value)) %>% 
  mutate(sig = ifelse(p.adj < 0.05, "sig", NA)) %>% ungroup() %>% 
  mutate(Compartment = fct_relevel(Compartment, "Soil", "Rhizo", "Root")) %>% 
  filter(!is.na(Phylum2)) %>% 
  ggplot(aes(Phylum2, Compartment, fill = estimate, alpha = sig)) +
  geom_tile(alpha = 1) +
  geom_tile(aes(color = sig, alpha = sig), size = 0.5, fill = NA) +
  scale_fill_gradient2(low = "gold", high = "darkorchid2") +
  scale_color_manual(values = c("black")) +
  scale_alpha_manual(values = c(0,1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "", y = "") +
  coord_equal()
```

